### ISSUE TITLE
status 502 for  No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by imyoungyang** [leodrak/ADFSCognito#1]
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://xxxxx.cloudfront.net' is therefore not allowed access. The response had HTTP status code 502.

**Comment by leodrak** [comment]
Is this error happening when you click Refresh on the Web UI after you have the JWT tokens?
If yes please Enable CORS manually on API Gateway via the AWS Management Console. Check the link below on how to:
https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html
I will try to replicate your issue as soon as possible

**Comment by leodrak** [comment]
ok I will try to replicate your issue and come back as soon as possible

**Comment by imyoungyang** [comment]
Thank you for your helps. It works now.

Related commit : https://github.com/leodrak/ADFSCognito/commit/f41419fb204062567a947279ffef50d97dbdf94d#diff-1a0887c6e67dc02292b5d15643d7f5d7
